{% set name = "kfp-notebook" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a616cb98738dfb790f0a175a8fef70b04784d932a599c2d7849d911f2be8b566

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - click >=6.0
    - bumpversion >=0.5.3
    - wheel >=0.30.0
    - watchdog >=0.8.3
    - flake8 >=3.5.0
    - tox >=2.9.1
    - coverage >=4.5.1
    - twine >=1.10.0
    - kfp >=0.5.1

test:
  imports:
    - kfp_notebook
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/elyra-ai/kfp-notebook
  dev_url: https://github.com/elyra-ai/kfp-notebook
  doc_url: https://github.com/elyra-ai/kfp-notebook/blob/master/README.md
  doc_source_url: https://github.com/elyra-ai/kfp-notebook/tree/master/docs
  license: Apache-2.0
  license_file: LICENSE
  summary: KFP-Notebook is an operator that enable running notebooks as part of a Kubeflow Pipeline
  description: >
    KFP-Notebook is an operator that enable running notebooks as part of a Kubeflow Pipeline

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
